### ISSUE TITLE
Missing file ''lesion_dict.json"

### ISSUE THREAD

**Issue by munanning** [mlii0117/FFA-IR#1]
Dear Mingjie:

Thanks for your carefully prepared dataset.

However, I find an important file lost:

**lesion_dict.json**: This file contains a dict to explain the index of each lesion in lesion_info.json. For each key-value pair, the key is the index of the lesion, the value provides both Chinese and English names of this lesion.

It is shown in the description, but not included in the zip.

**Comment by mlii0117** [comment]
Hi Munan,

Thanks for your interest. I have sent it to you, and we will update the version on Physionet.

Keep in touch.

**Comment by mlii0117** [comment]
Hi Munan,

Thanks for your interest. I have sent it to you, and we will update the version on Physionet.

Keep in touch.

**Comment by kixcodes** [comment]
Dear Mingjie, I also have this issue and the Physionet was unfortunately not updated. Is it possible to receive the file in another way?
